import torch
import matplotlib.pyplot as plt

class Model:

    def __init__(self, time, ncomp, burstparams, ybkg=0.0):
        self.time = time
        self.n_components = ncomp
        
        # (bs, n)
        self.t0 = burstparams['t0']
        bs, n = self.t0.shape

        self.amp = burstparams['amp']
        self.rise = burstparams['rise']
        self.skew = burstparams['skew']
        self.ybkg = ybkg

        # expand fixed params
        self.amp = torch.broadcast_to(self.amp, (bs, n))
        self.rise = torch.broadcast_to(self.rise, (bs, n))
        self.skew = torch.broadcast_to(self.skew, (bs, n))
        self.time = torch.broadcast_to(self.time, (bs, len(time)))

        if sum([len(param[0]) for param in [self.amp, self.rise, self.skew, self.t0]]) != 4*ncomp:
            raise ValueError("`burstparams` must contain all burst model parameters!")

        self.flux = self.lightcurve_model()

    def single_component(self, k):
        """
        Calculate a double-sided exponential at 
        all time steps `t` for the given parameters.
        
        The double-sided exponential consists of a 
        positive exponential $amp exp((time-t0)/rise)$ for 
        times $time <= t0$, and a negative exponential 
        $amp exp(-(time-t0)/(s*rise)$ for times $ttime > t0$.
        
        Parameters
        ----------
        k: int
            Index of the component (first component k=0, second component k=1, ...)

        Returns
        -------
        model : numpy.ndarray
            An array of the same size of $t$, returning the 
            model flux for each time step
        """
        t0   = self.t0[:, k].reshape(-1, 1)
        rise = self.rise[:, k].reshape(-1, 1)
        amp  = self.amp[:, k].reshape(-1, 1)
        skew = self.skew[:, k].reshape(-1, 1)

        tdiff = (self.time - t0) / rise

        tdiff_before_t0 = torch.where(self.time <= t0, tdiff, torch.nan)
        tdiff_after_t0 = torch.where(self.time > t0, tdiff, torch.nan)

        flux_before_t0 = amp * torch.exp(tdiff_before_t0)
        flux_after_t0  = amp * torch.exp(-tdiff_after_t0/skew)
        
        flux = torch.nan_to_num(flux_before_t0) + torch.nan_to_num(flux_after_t0)
        
        return flux

    def lightcurve_model(self):
        """
        This function takes an arbitrary number of components 
        generated by the `single_component` function and linearly sums them 
        all together. 
            
        Returns
        -------
        model : numpy.ndarray
            An array of the same size of $t$, returning the 
            model flux for each time step
        """
        # reset the model
        flux = torch.zeros_like(self.time)
        
        for k in range(self.n_components):
            flux += self.single_component(k)
            
        flux += self.ybkg
        return flux

    def get_flux(self):
        return self.flux

    def get_parameter_dict(self):
        return {
            't0':self.t0,
            'amp': self.amp,
            'rise': self.rise,
            'skew': self.skew,
            'ybkg': self.ybkg,
            'ncomp': self.n_components
        }
