import numpy as np
import matplotlib.pyplot as plt

class Model:

    def __init__(self, time, ncomp, burstparams, ybkg=0.0):
        if sum([len(burstparams[param]) for param in burstparams]) != 4*ncomp:
            raise ValueError("`burstparams` must contain all burst model parameters!")

        self.time = time
        self.n_components = ncomp
        
        self.t0 = burstparams['t0']
        self.amp = burstparams['amp']
        self.rise = burstparams['rise']
        self.skew = burstparams['skew']
        self.ybkg = ybkg

        self.flux = self.lightcurve_model()

    def single_component(self, k):
        """
        Calculate a double-sided exponential at 
        all time steps `t` for the given parameters.
        
        The double-sided exponential consists of a 
        positive exponential $amp exp((time-t0)/rise)$ for 
        times $time <= t0$, and a negative exponential 
        $amp exp(-(time-t0)/(s*rise)$ for times $ttime > t0$.
        
        Parameters
        ----------
        k: int
            Index of the component (first component k=0, second component k=1, ...)

        Returns
        -------
        model : numpy.ndarray
            An array of the same size of $t$, returning the 
            model flux for each time step
        """
        t0   = self.t0[k]
        rise = self.rise[k]
        amp  = self.amp[k]
        skew = self.skew[k]

        tdiff = (self.time - t0) / rise
        
        flux = np.zeros_like(self.time)
        flux[self.time <= t0] = amp * np.exp(tdiff[self.time <= t0])
        flux[self.time > t0] = amp * np.exp(-tdiff[self.time > t0]/skew)
        
        return flux

    def lightcurve_model(self):
        """
        This function takes an arbitrary number of components 
        generated by the `single_component` function and linearly sums them 
        all together. 
            
        Returns
        -------
        model : numpy.ndarray
            An array of the same size of $t$, returning the 
            model flux for each time step
        """
        # reset the model
        flux = np.zeros_like(self.time)
        
        for k in range(self.n_components):
            flux += self.single_component(k)
            
        flux += self.ybkg
        return flux

    def get_flux(self):
        return self.flux

    def get_parameter_dict(self):
        return {
            't0':self.t0,
            'amp': self.amp,
            'rise': self.rise,
            'skew': self.skew,
            'ybkg': self.ybkg,
            'ncomp': self.n_components
        }

class BurstSimulator:

    def __init__(self, model):
        """
        Parameters
        ----------
        model : Model
            An array of the same size of $t$, returning the 
            model flux for each time step
        """
        self.model = model
    
    def simulate_burst(self, return_model=False):
        """
        Simulate a realistic burst by adding poisson noise
        to the model.
            
        return_model : bool, default False
            If True, return the model flux (without Poisson
            counts) along with the Poisson-drawn model 
            counts. If False, just contain the Poisson counts

        Returns
        -------
        x_counts : numpy.ndarray
            An array of the same size of $t$, returning the 
            simulated counts    
        """
        model = self.model.get_flux()
        self.simulated_counts = self.add_poisson_noise(model)

        if return_model:
            return self.model, self.simulated_counts
        else:
            return self.simulated_counts

    def add_poisson_noise(self, model):
        """
        Adds poisson noise to the modelled light curve
        """
        counts = np.random.poisson(model)
        return counts

    def get_true(self, param: str):
        """
        Returns true value of a given burst parameter. 
        """
        true_value = self.model.get_parameter_dict().get(param, None)
        if true_value == None:
            print("INVALID PARAMETER KEY GIVEN")
        return true_value

    def plot_burst(self):
        """
        Display a plot of a single simulated burst with and without noise.
        """
        if np.sum(self.simulated_counts) == 0 or np.sum(self.model) == 0:
            print("NO MODEL / SIMULATION TO PLOT")

        time = self.model.time
        true_flux = self.model.get_flux()

        plt.plot(time, self.simulated_counts, color="black", label="Poisson model counts")
        plt.plot(time, true_flux, color="orange", label="Noise-free model")
        plt.xlabel("Time [arbitrary units]")
        plt.ylabel("Flux [arbitrary units]")
        plt.xlim(time[0], time[-1])
        plt.legend()